[supervisord]
nodaemon=true

[program:cncjs]
command=/usr/local/bin/cncjs -H 0.0.0.0 -p 80 -c /config/cncrc
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:socat]
# http://supervisord.org/configuration.html#environment-variables
# http://supervisord.org/configuration.html#program-x-section-settings
command=/usr/bin/socat pty,link=/dev/tty.esplink,raw,echo=0 tcp:%(ENV_ESPLINK_HOST)s:23
stopwaitsecs=30
# it requires a normal connection manager (not 1000 retries)
startretries=1000
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0